src/components/NewsletterSignup.js
src/components/SharedStyledComponents.js
src/lambda/inquiry.js
src/lambda/newsletter-signup.js
src/pages/explore.js
src/pages/index.js
src/pages/project.js
src/utils/styles.js

Add newsletter signup

---

src/pages/local-grants/honduras/en.md
src/pages/local-grants/honduras/es.md

I edited a few grammatical things (changing lower case letters to upper case) and removed some text.

Edited application submission details

---

src/pages/local-grants/honduras/en.md
src/pages/local-grants/honduras/es.md

Updated Honduras flyer pages with post deadline message

---

src/pages/local-grants/honduras/es.md

Fixed typo in Spanish post deadline message

---

src/pages/wishlist.js

Add pinboard URL

---

src/components/MobileNavLinks.js

- Make mobile nav scrollable
- Adjust height of mobile nav
#45

Make mobile nav scrollable [Fixes #45]

---

src/pages/grantee-finance-form.js

Add max length to input fields to avoid Salesforce API failures.
None

Add max lengths to grantee form fields

---

src/pages/local-grants/colombia/en.md

* Clarified program details
* Translated intro to Spanish

Edited Colombia flyer text to include suggested changes

---

src/pages/local-grants/colombia/en.md

* Changed opening tldr language back to English, seeing that we'll have a full on Spanish version as well

Reverted tldr of eng version of co flyer to english

---

src/pages/local-grants/colombia/en.md

Edited flyer question

---

src/pages/local-grants/honduras/en.md
src/pages/local-grants/honduras/es.md

* Updated both English and Spanish versions of Honduras LG flyer to signal pilot is over

Updated both version of Honduras flyer to signal pilot is over

---

netlify.toml
src/pages/local-grants/colombia/en.md
src/pages/local-grants/colombia/es.md
src/pages/local-grants/honduras/en.md
src/pages/local-grants/honduras/es.md
src/templates/static.js

Add colombia translation

---

src/pages/local-grants/colombia/en.md
src/pages/local-grants/colombia/es.md

Edited Spanish title for Colombia LGP es flyer

Edited Spanish title for Colombia LGP es flyer

---

src/pages/about.js
src/pages/faq.js
src/pages/local-grants/honduras/en.md
src/pages/local-grants/honduras/es.md
src/pages/wishlist.js

Update /project links to /inquire
None

Fix broken /project links

---

src/pages/local-grants/colombia/en.md
src/pages/local-grants/colombia/es.md

Changed link under Support section

Changed esp link for more info

---

src/components/LocalGrantsForm.js
src/intl/en.json
src/intl/es.json
src/utils/form-inputs.js

Add 'Newsletter' as Referral Source option
#53

Add 'Newsletter' as Referral Source option [Fixes #53]

---

package.json
src/components/Event.js
src/components/GuideNav.js
src/components/MobileNavLinks.js
src/components/Nav.js
src/components/NavDropdown.js
src/components/ProjectCard.js
src/intl/en.json
src/lambda/inquiry.js
src/pages/grants.js
src/pages/support.js
src/utils/styles.js
yarn.lock

- Add "Grants" page
- Add "Support" page
- Add both pages to site nav via "About" dropdown
None

Grants & Support pages

---

src/components/SharedStyledComponents.js
src/intl/en.json
src/intl/es.json
src/pages/index.js
src/pages/support.js

- Fix "impact" translation key [Fixes #67]
- Update ButtonLink to use Link component [Fixes #66]
#67 #66

Homepage link fix

---

src/pages/local-grants/colombia/en.md
src/pages/local-grants/colombia/es.md

Removed submission form and updated flyer versions with post LGP copy

Removed submission form and updated flyer versions with post LGP copy

---

src/components/RollupGrantsForm.js

- Changes `&` to `and` on projectCategories to be consistent with SF backend
- Adds small `Ex:` text to some items for clarity
- Added twitter handle char limit (15)
- Couple small naming adjustments

Rollup Grants Form patch

---

src/pages/index.js

Removes leftover `console.log()` on IndexPage from recent changes

Remove stray console.log

---

src/pages/rollup-grants/en.md

- "Its might..." -> "It might..."
- "validators" -> "verifiers"

Typo fixes

---

src/components/RollupGrantsForm.js

- Additional form validation added to RollupGrantsForm. Checks for valid email address, and also checks for valid LinkedIn URL (IF it's not blank, as it's not required)
- Places <small> red error message under problematic fields if submitted with invalid email/URL
- Adds small text reminder to fill out all required fields while the button is disabled.

Adds form validation to RollupGrantsForm

---

src/components/RollupGrantsForm.js

Update to match the field in SF

Fix PROJECT_CATEGORIES options

---

src/components/Layout.js
src/components/PageMetadata.js
src/components/RollupGrantsForm.js
src/pages/index.js

- Updated class-based components to functional components using hooks. (Layout.js, index.js)
- Cleaned up some console warnings

Hooks refactor, warning cleanup

---

src/pages/rollup-grants/en.md

Updates Rollup Grants page with alert that grand round deadline has passed.

Rollup Grants deadline passed alert

---

src/pages/rollup-grants/en.md

- Typo fix
- Removed deprecated copy

Post-rollup cleanup

---

src/pages/devcon-grants/en.md
src/pages/devcon-grants/zh.md

- Updates deadline to Aug 8 in two places that were missed
- Updates with devcon email on zh version

Devcon patch

---

src/components/DevconGrantsForm.js
src/intl/en.json
src/intl/zh.json

Add validation for input date on devcon form
Validation now checks that the date is a valid date in the future of the current date.
Fixes: https://github.com/ethereum/esp-website/issues/102

Validate date input for devcon form

---

src/lambda/grantee.js
src/pages/grantee-finance-form.js

Update copy
Remove Bank routing number field
Fixes: https://github.com/ethereum/esp-website/issues/110

Grantee Payment Form Update 

---

src/actions/ProcessActions.ts
src/actions/index.ts
src/components/UI/List.tsx
src/components/UI/NavMobile.tsx
src/components/UI/Step/StepArrow.tsx
src/components/UI/Step/StepHeader.tsx
src/components/UI/Step/StepReadMore.tsx
src/components/UI/Step/index.ts
src/components/UI/VisuallyHiddenText.tsx
src/components/UI/headings/StepHeading.tsx
src/components/UI/headings/index.ts
src/components/UI/icons/index.ts
src/components/UI/index.ts
src/pages/_document.tsx
src/pages/applicants/project-grants.tsx
src/public/images/step-polygon.svg
src/reducers/index.ts
src/reducers/processReducer.ts

This PR adds the Process section for `/applicants/project-grants` (mobile version)
PREVIEW: https://deploy-preview-117--thirsty-meitner-cae269.netlify.app/applicants/project-grants
- `StepHeading` component added to `/UI/headings`
- `/UI/Step` components added
- `List` component added to `/UI`
- `VisuallyHiddenText` component added
- `_document.tsx` page added and html lang set to `en`
- `/actions` and `/reducers` added, to handle Process section state w/`useReducer`

Applicants project grants mobile process

---

src/components/UI/common/ReadyToApply.tsx
src/pages/_app.tsx

- Modifies the `ReadyToApply` component to use an `a` tag instead of button

chore: use a tag instead of button for apply link

---

src/components/UI/FAQItem.tsx

This PR removes the left margin **A.** section from FAQ items

chore: remove A. from FAQ items

---

src/components/UI/common/NewsletterSignup.tsx
src/components/UI/common/ReadyToApply.tsx
src/hooks/index.ts
src/hooks/placeholder.txt
src/hooks/useShadowAnimation.ts
src/theme.ts

This PR adds hover animation to Apply & Signup buttons
- adds `useShadowAnimation` custom hook
- use `MotionBox` and `MotionFlex` instead of plain `Box` & `Flex` components to enable translate animation
- adds shadow `Box` component to use it on sibling button hover
- adds `translateX`, `translateY` on button hover
- adds shadow color to `theme.ts`

Buttons animation

---

src/components/UI/common/DropdownIndicator.tsx
src/components/UI/common/ThankYouBody.tsx
src/components/UI/common/index.ts
src/components/forms/Forms.tsx
src/components/forms/OfficeHoursForm.tsx
src/components/forms/ProjectGrantsForm.tsx
src/components/forms/constants.ts
src/components/forms/index.ts
src/constants.ts
src/pages/applicants/office-hours/apply.tsx
src/pages/applicants/office-hours/thank-you.tsx
src/pages/applicants/project-grants/apply.tsx
src/pages/applicants/project-grants/thank-you.tsx
src/theme.ts
src/types.ts

This PR adds the Office Hours form
- adds Office Hours form (without validation)
- adds `ThankYouPageBody` component
- adds Office Hours Thank You page
- adds `Radio` and `Checkbox` custom styles to `theme.ts`
- update constants

Office hours apply page

---

src/components/UI/common/Footer.tsx

This PR updates the `Footer` component layout for mobile
- updates the footer layout to use a single column for mobile and match the current design

chore: update footer layout on mobile to column instead

---

src/pages/index.tsx
src/theme.ts

This PR adds a note below homepage' stats section and fixes font sizes for mobile.
- adds note below stats section 
- adds responsive font size for smaller screens on mobile
- adds `allocations` font size to `theme`

Homepage stats updates

---

.env.local.example
package.json
src/components/forms/NewsletterSignup.tsx
src/constants.ts
src/pages/api/newsletter-signup.ts
yarn.lock

Integration with Mailchimp when a user signup to the newsletter.
- I have also created a `.env.local.example` file to have a reference of all the env vars that we have in the app.

Mailchimp integration

---

netlify.toml

Adds redirects for the new ESP redesign.

Redirects for the new redesign

---

src/components/layout/Layout.tsx
src/pages/404.tsx
src/pages/_app.tsx

Page not found

---

src/pages/_app.tsx

This PR fixes the bg gradient for homepage on mobile

fix: homepage mobile bg gradient

---

src/components/forms/ProjectGrantsForm.tsx
src/pages/api/project-grants.ts
src/types.ts

This PR fixes the Project Grants form submission when no (optional) file was attached, currently failing

fix: submit Project Grants lead without file

---

src/pages/api/newsletter-signup.ts

Adds NEWSLETTER merge field to the newsletter subscription.

Add newsletter merge field

---

src/components/UI/AcademicGrantsHero.tsx
src/components/UI/common/ThankYouBody.tsx
src/constants.ts
src/pages/academic-grants/apply.tsx
src/pages/academic-grants/index.tsx
src/pages/academic-grants/thank-you.tsx

Update academic content + small refactor on the use of email constants.

Update academic content

---

src/components/forms/AcademicGrantsForm.tsx

Update academic form copy to incorporate feedback from @ethjoe.
None

Update academic form copy

---

src/pages/academic-grants/index.tsx

Add academics grants description

---

netlify.toml
src/components/UI/AcademicGrantsHero.tsx
src/components/UI/OrderedList.tsx
src/components/forms/DevconGrantsForm.tsx
src/components/forms/Forms.tsx
src/components/forms/SmallGrantsForm.tsx
src/components/forms/api.ts
src/components/forms/constants.ts
src/components/forms/index.ts
src/components/forms/selectStyles.ts
src/components/layout/AcademicGrantsLayout.tsx
src/components/layout/DevconGrantsLayout.tsx
src/components/layout/Layout.tsx
src/constants.ts
src/pages/api/academic-grants.ts
src/pages/api/devcon-grants.ts
src/pages/devcon-grants/apply.tsx
src/pages/devcon-grants/index.tsx
src/pages/devcon-grants/thank-you.tsx
src/types.ts
src/utils/getBgGradient.ts
src/utils/getLayoutHeight.ts

Adds Devcon grants application.
Preview https://deploy-preview-190--ecosystem-support.netlify.app/devcon-grants

Devcon grants page

---

src/components/forms/GranteeFinanceForm.tsx
src/components/forms/api.ts
src/pages/api/grantee-finance/dai.ts
src/pages/api/grantee-finance/eth.ts
src/types.ts

This PR adds L2 payment option w/radio button to Grantee Finance form
- adds `L2Payment` field
- updates `/grantee-finance` API route to send the proper data
closes #139

L2 grantee finance payments

---

src/components/layout/DevconGrantsLayout.tsx
src/constants.ts
src/pages/devcon-grants/index.tsx

Adds links to the Devcon website.

Devcon links

---

netlify.toml
next-sitemap.js
package.json
public/robots.txt
public/sitemap-0.xml
public/sitemap.xml
src/constants.ts
yarn.lock

This PR adds `sitemap.xml` to ESP site
- adds `next-sitemap` package to generate sitemaps
- updates `robots.txt`

Add sitemap

---

src/components/UI/PageMetadata.tsx
src/components/forms/selectStyles.ts
src/pages/about/how-we-support.tsx
src/pages/academic-grants/apply.tsx
src/pages/academic-grants/thank-you.tsx
src/pages/applicants/grantee-finance/thank-you.tsx
src/pages/applicants/index.tsx
src/pages/applicants/office-hours/apply.tsx
src/pages/applicants/office-hours/index.tsx
src/pages/applicants/office-hours/thank-you.tsx
src/pages/applicants/project-grants/apply.tsx
src/pages/applicants/project-grants/index.tsx
src/pages/applicants/project-grants/thank-you.tsx
src/pages/applicants/small-grants/apply.tsx
src/pages/applicants/small-grants/index.tsx
src/pages/applicants/small-grants/thank-you.tsx
src/pages/devcon-grants/apply.tsx
src/pages/devcon-grants/thank-you.tsx
src/pages/index.tsx

Add additional meta tags

---

src/components/forms/GranteeFinanceForm.tsx

This PR updates some form inputs as described in #214

Grantee Finance Form updates

---

src/components/UI/common/ThankYouBody.tsx
src/components/forms/SmallGrantsForm.tsx
src/components/forms/api.ts
src/pages/api/small-grants/event.ts
src/pages/api/small-grants/project.ts
src/types.ts

- Updates small grants form per notion docs / google sheet
Google sheet: https://docs.google.com/spreadsheets/d/1l5t3ar-pbJwzjeNtm-xd7fdGC3EVTWnTzDQ98gOGjn4/edit#gid=0
Notion doc: https://www.notion.so/efdn/Complete-List-of-Web-Form-Edits-for-Website-Team-d131db987707417690ee72fd4a7b3491
Current live form page: https://esp.ethereum.foundation/applicants/small-grants/apply
Preview page: https://deploy-preview-217--ecosystem-support.netlify.app/applicants/small-grants/apply

Update small grants form

---

src/components/forms/OfficeHoursForm.tsx
src/pages/applicants/office-hours/apply.tsx

- Small copy update to office hours application form per request

Office house form copy update

---

src/pages/merge-data-challenge/apply.tsx

- Add left, right, bottom padding for the merge data challenge apply hero

Add padding to merge data challenge apply hero

---

src/pages/devcon-grants/index.tsx

- Removes a line item per issue #229

Remove line item [Closes #229]

---

src/pages/merge-data-challenge/apply.tsx
src/pages/merge-data-challenge/index.tsx

- Adds a link to the ethstaker merge data challenge channel on discord

Ethstaker merge data challenge channel link

---

src/components/Banners.tsx

Update banner with semaphore grants link.

Update banner with Semaphore link

---

src/pages/api/merge-data-challenge.ts

Update spreadsheet params for the merge challenge applications.
#242

Fix merge challenge sheet integration

---

src/pages/semaphore-grants/index.tsx

**THIS WILL TO BE MERGED ON OCT 7TH**
Update semaphore deadline to October 28th.
#235

[DO NOT MERGE] Update semaphore deadline

---

src/components/forms/constants.ts

This PR fixes the `category` options to match the ones from SF.

Fix category option values

---

src/pages/about/index.tsx

Add video in about page

---

src/components/layout/Layout.tsx

This PR addresses this issue #252

Hide the newsletter

---

src/pages/api/project-grants.ts

Reverting [this change](https://github.com/ethereum/esp-website/pull/255/files#diff-8c3c7f60b3c1f8846dbeaffd6c8499398e7a7ee27ebf19cfd1d248ad8986b849) that was introduced by mistake on a recent PR.

Fix project grants record type

---

package.json
src/middlewares/index.ts
src/middlewares/sanitizeFields.ts
src/pages/api/academic-grants-2023.ts
src/pages/api/devcon-grants.ts
src/pages/api/ecodev-grants.ts
src/pages/api/grantee-finance.ts
src/pages/api/office-hours.ts
src/pages/api/project-grants.ts
src/pages/api/small-grants/event.ts
src/pages/api/small-grants/project.ts
yarn.lock

As a quick solution to mitigate the issues detected on the `firstName` and `lastName` fields, we implement this middleware to sanitize these two fields. Later, we plan to implement a more robust solution which include the definition of data schemas with https://zod.dev/ and validate the data against that schema.
Adds a new middleware to sanitize the text fields.

Add fields sanitizer middleware

---

src/components/forms/AcademicGrants2023Form.tsx

As requested by Rodrigo, set the `website` field as required.

Website field as required

---

src/components/forms/EcodevGrantsForm.tsx
src/components/forms/ProjectGrantsForm.tsx
src/components/forms/SmallGrantsForm.tsx

Update the `Referrals` field type to be a TextArea.
#268

Update referrals field type

---

src/components/forms/constants.ts

Fix category option

---

src/components/forms/constants.ts

Update options to match the corresponding field in SF side.

Update options for "applyingAs" field

---

src/pages/account-abstraction-grants/index.tsx

Fix application link

---

src/components/UI/common/Description.tsx
src/components/layout/AcademicGrantsApplyLayout.tsx
src/components/layout/DevconGrantsLayout.tsx
src/pages/devcon-grants/index.tsx
src/utils/getBgGradient.ts

Updates copy.
Preview link: https://deploy-preview-284--ecosystem-support.netlify.app/devcon-grants

Devcon Grants - Update copy

---

src/constants.ts
src/pages/devcon-grants/apply.tsx
src/pages/devcon-grants/index.tsx

Update Devcon copy

---

src/pages/devcon-grants/apply.tsx
src/pages/devcon-grants/index.tsx

More copy updates for the Devcon landing page & metadata.

Update Devcon copy 2

---

src/pages/run-a-node-grants/index.tsx

Update the deadline to June 20th.

Fix deadline for Run a node grants

---

src/components/layout/RunANodeGrantLayout.tsx
src/pages/run-a-node-grants/index.tsx

Update run a node page description

---

src/components/layout/RunANodeGrantLayout.tsx
src/pages/run-a-node-grants/index.tsx

Edits to the copy for the run a node page

Copy edit to Run a Node

---

src/components/forms/fields/Captcha.tsx

Revalidate form after captcha is verified.

Revalidate Captcha field

---

src/components/UI/common/PrivacyPolicyAgreement.tsx
src/components/UI/common/index.ts
src/pages/applicants/office-hours/apply.tsx
src/pages/applicants/project-grants/apply.tsx
src/pages/applicants/small-grants/apply.tsx

Upon request, note about agreeing to privacy policy added at the end of each introduction for:
- `/applicants/office-hours/apply`
- `/applicants/small-grants/apply`
- `/applicants/project-grants/apply`

Add privacy policy agreement

---

src/pages/api/devcon-grants.ts
src/pages/api/ecodev-grants.ts
src/pages/api/office-hours.ts
src/pages/api/project-grants.ts
src/pages/api/small-grants/event.ts
src/pages/api/small-grants/project.ts

Adds the `LeadSource` field to every lead form submission with the hardcoded value `Webform`.

LeadSource field

---

src/pages/api/devcon-grants.ts
src/pages/devcon-grants/index.tsx

This PR addresses the following:
- Updates the copy of the landing page
- Change the "Proactive_Community_Grants_Round__c" field value to "Road to Devcon 7"

Devcon updates

---

src/pages/data-collection-grants/index.tsx

Fixes the copy in the FAQ section.

Data Collection grants - fix copy

---

src/pages/api/ecodev-grants.ts

Sends the `Pipeline_Entry__c` field with value `EcoDev`.

Ecodev - add pipeline entry field

---

src/pages/api/data-collection-grants.ts

Adds `LeadSource` field in data collection submissions.

Set LeadSource field in Data Collection

---

src/pages/applicants/office-hours/thank-you.tsx

Changes the Thankyou page body copy for the Office Hours grants.
Requested in the Discord ESP channel.

Change the Thankyou copy for the Office Hours grants page

---

src/pages/devcon-grants/index.tsx

Updates the copy for the devcon grants page.
Preview: https://deploy-preview-324--ecosystem-support.netlify.app/devcon-grants
Requested by the ESP team.

Devcon grants page - update copy

---

src/components/forms/GranteeFinanceForm.tsx

Displays a warning message on the Notes field when the bank is from India.
Preview: https://deploy-preview-322--ecosystem-support.netlify.app/applicants/grantee-finance
Fixes #312

Warning message for Indian banks

---

src/components/forms/ProjectGrantsForm.tsx
src/components/forms/SmallGrantsForm.tsx
src/pages/api/small-grants/event.ts
src/types.ts

Makes the Country field as required and adds the new Community Event field in Small & Project grants.
Preview small grants: https://deploy-preview-323--ecosystem-support.netlify.app/applicants/small-grants/apply
Preview project grants: https://deploy-preview-323--ecosystem-support.netlify.app/applicants/project-grants/apply
Fixes #321

Country Field Required & New Community Event Field

---

src/components/forms/SmallGrantsForm.tsx
src/pages/applicants/small-grants/apply.tsx

Fixes `eventLocation` input type (should be `text`)

fix: eventLocation input type

---

src/components/forms/AcademicGrantsForm.tsx

Show a missing required icon for a required field.

Show required icon

---

src/pages/api/academic-grants.ts
src/pages/api/ecodev-grants.ts
src/pages/api/project-grants.ts
src/utils/truncateString.ts

Truncates filenames to fix possible `STRING_TOO_LONG` error on SF.

Truncate filenames

---

src/constants.ts
src/pages/zk-grants/index.tsx

Use the zk hero image for the og image.

zk custom og image

---

src/components/Banners.tsx
src/components/layout/DataChallengeLayout.tsx
src/pages/api/data-challenge-grants.ts
src/pages/data-challenge-4844/apply.tsx
src/pages/data-challenge-4844/index.tsx
src/pages/data-challenge-4844/thank-you.tsx

From `Data Challenge 4844` to `4844 Data Challenge`.

Change Data Challenge name

---

src/components/forms/OfficeHoursForm.tsx
src/components/forms/api.ts
src/pages/api/office-hours.ts
src/types.ts

Added country field to the office hours webform.
- Resolves #332
- I couldn't test with Salesforce, so someone may need to test on their end!

feat: add country to office hours webform

---

src/components/forms/constants.ts

Updates the project categories used in the Office hours, Small grants, and Project grants forms.
#349

Update project category options

---

src/components/forms/GranteeFinanceForm.tsx
src/components/forms/api.ts
src/components/forms/constants.ts
src/pages/api/grantee-finance.ts
src/types.ts

Adds new fields in grantee finance form.
Preview: https://deploy-preview-365--ecosystem-support.netlify.app/applicants/grantee-finance
Fixes #360

Add new fields in grantee finance form

---

src/components/forms/api.ts

Adds check to default `l2Network` to empty string.

Fix `undefined` issue with `l2Network` field

---

src/pages/index.tsx

Updates the home page stats and switches the project & amount texts.
Fixes #361

Update home page stats

---

src/pages/account-abstraction-grants/index.tsx
src/pages/zk-grants/index.tsx

chore: fix some typos in comments

---

netlify.toml
src/constants.ts
src/pages/about/who-we-support.tsx
src/types.ts

Updates the grants list displayed in "who we support" page.
Preview: https://deploy-preview-373--ecosystem-support.netlify.app/about/who-we-support
#362

Update "Who We Support" grants list

---

src/pages/data-challenge-4844/index.tsx

Data challenge - updated copy

---

src/components/forms/GranteeFinanceForm.tsx
src/components/forms/api.ts
src/pages/api/grantee-finance.ts
src/types.ts

Adds new `isCentralizedExchange` field on the Grantee Finance form.
Closes #381

Grantee Finance form: Centralized Exchange Checkbox

---

src/components/forms/GranteeFinanceForm.tsx
src/components/forms/constants.ts
src/pages/api/grantee-finance.ts
src/types.ts

Updates fields in the Grantee Finance Form.
Preview: https://deploy-preview-384--ecosystem-support.netlify.app/applicants/grantee-finance
closes #383

Update fields on Grantee Finance Form

---

src/components/forms/GranteeFinanceForm.tsx

Adds the alert in the grantee finance form.
https://deploy-preview-390--ecosystem-support.netlify.app/applicants/grantee-finance
Closes #389

Alert for korean banks

---

src/pages/devcon-grants/index.tsx

Updates content for `/devcon-grants`.
https://deploy-preview-392--ecosystem-support.netlify.app/devcon-grants
Closes #391

Devcon satellite events

---

.env.local.example
package.json
src/components/AGRMailingForm.tsx
src/components/UI/common/BannerApplicationClosed.tsx
src/pages/academic-grants/index.tsx
src/pages/api/agr-mailing.ts
yarn.lock

Adds a form to subscribe to the agr mailing list.
https://deploy-preview-388--ecosystem-support.netlify.app/academic-grants

AGR mailing list form

---

src/pages/devcon-grants/index.tsx

Update Satellite Events dates

---

src/components/AGRMailingForm.tsx
src/pages/api/agr-mailing.ts

Displays a better message when the email already exists in the mailing list.
Fixes #405

Better error message in agr mailing form

---

src/pages/pectra-pgr/index.tsx

Adds underline for links in pectra pgr page

add underline to links

---

src/components/layout/AcademicGrantsLayout.tsx
src/pages/academic-grants/index.tsx

Update AGR deadline to march 23rd

Update AGR deadline

---

src/components/forms/AcademicGrantsForm.tsx
src/components/forms/schemas/AcademicGrants.ts
src/components/forms/schemas/DataChallenge4844.ts
src/components/forms/schemas/DataCollection.ts
src/components/forms/schemas/PectraPGR.ts
src/components/forms/schemas/RunANode.ts
src/components/forms/schemas/ZKGrants.ts

Sets a 255 char limit in all `referralSourceIfOther` fields.

Patch `Referral_Source_if_Other__c` field max char limit

---

src/components/Banners.tsx
src/components/layout/AcademicGrantsLayout.tsx
src/constants.ts
src/pages/academic-grants/apply.tsx
src/pages/academic-grants/index.tsx
src/pages/academic-grants/thank-you.tsx

Reverts the closing of AGR and extends deadline to March 25th.

Revert close AGR & update deadline

---

src/components/Banners.tsx

Adds destino devconnect grants to banner

add destino devconnect to banner

---

src/components/forms/DestinoDevconnectForm.tsx
src/components/forms/constants.ts
src/components/forms/schemas/DestinoDevconnect.ts
src/pages/api/destino-devconnect.ts

Destino non-financial category

---

src/components/forms/DestinoDevconnectForm.tsx
src/components/forms/schemas/DestinoDevconnect.ts
src/pages/api/destino-devconnect.ts

nonfinancial support field
