- gatsby-config.js
- Filter out base pages that don't have a language directory
- Filter out 404 pages
> Remove duplicate pages from sitemap

- gatsby-config.js
Our internationalization plugin was [redirecting traffic based on the user's browser preference](https://github.com/wiziple/gatsby-plugin-intl#how-it-works). This led to issues of redirecting users to pages that did not exist (e.g. someone with browser language set to Spanish landing on esp.ethereum.foundation/ was being redirected to esp.ethereum.foundation/es/, which does not exist).
The reason this was an issue is because the only page we actually have translated into Spanish is https://esp.ethereum.foundation/es/local-grants/honduras/ 
#32
> Avoid lang redirects [Fixes #32]

- gatsby-config.js
- package.json
- src/components/PageMetadata.js
- src/utils/translations.js
- yarn.lock
To fix #32 I had to remove the redirect functionality of [our internationalization plugin](https://github.com/wiziple/gatsby-plugin-intl). This resulted in both the base paths & English paths resolving as English (e.g. both https://esp.ethereum.foundation/about/ & https://esp.ethereum.foundation/en/about/), which creates a duplicate content issue.
This PR adds a [canonical tag](https://support.google.com/webmasters/answer/139066?hl=en) to every page, specifying the appropriate language path (e.g. so the canonical tag on https://esp.ethereum.foundation/about/ is set to https://esp.ethereum.foundation/en/about/).
#32
> Add canonical tags

- src/templates/static.js
Adds in a `Divider` component. This was utilized in the RollupGrantsForm markdown, but the component did not exist. Added using footer divider as style guide.
> Adds Divider component to static template

- src/pages/index.js
Adds `import "@fortawesome/fontawesome-svg-core/styles.css"` to `src/pages/index.js` alleviating the flickering arrow icon glitch when the page loads.
> Import "@fortawesome/fontawesome-svg-core/styles.css" [Fixes #82]

- src/pages/grants.js
- src/pages/index.js
- src/pages/rollup-grants/en.md
- Removes form from `rollup-grants` page
- Removes links/references to this page
- Leaves the markdown page to avoid breaking any existing external links
- Updates copy on this page to indicate past tense now that deadline has passed
> Remove rollup grant form

- src/pages/grants.js
Adds the below links to grants page
- 2021 Q1 https://blog.ethereum.org/2021/07/01/esp-allocation-update-q1-2021/
- 2020 Q4 https://blog.ethereum.org/2021/03/22/esp-allocation-update-q4-2020/
> Adds links to latest quarterly blog updates

- package.json
- src/pages/_app.tsx
- yarn.lock
This PR removes the focus outline from clickable components (i.e.: accordion items, tabs) for non-keyboard interactions.
- removes the focus outline for non-keyboard interactions (click focus)
- preserves the outline for keyboard navigation on keyboard focus, [required for a11y](https://github.com/chakra-ui/chakra-ui/issues/708#issuecomment-628131464)
> chore: disable focus outline for non-keyboard interactions

- src/pages/index.tsx
This PR improves homepage `stats` grid responsiveness on desktop layouts (1366x768, 1080p resolutions)
> fix: stats grid on desktop

- src/pages/api/small-grants/project.ts
This PR removes `trim()` from the `repeatApplicant` value, which is a boolean, causing the `Small Grants` submission to fail
> fix: remove trimming from repeatApplicant value

- src/components/forms/ProjectGrantsForm.tsx
- src/constants.ts
- src/pages/api/project-grants.ts
This PR updates the file size limit for Project Grants (currently set to 1mb) to the [maximum of 4mb](https://nextjs.org/docs/messages/api-routes-body-size-limit)
> Update pg file size limit

- src/components/forms/api.ts
- src/utils/addTimestamp.ts
- src/utils/index.ts
This PR removes the timestamp from lead's email as it's not required anymore
> Remove timestamp from email

- netlify.toml
Add redirect on old page:
https://esp.ethereum.foundation/en/grantee-finance-form
Now lives at:
https://esp.ethereum.foundation/applicants/grantee-finance
None
> Add grantee page redirect

- netlify.toml
Removed cookie policy redirect as the page doesn't exist.
> Fix cookie policy redirect

- netlify.toml
`from = "/*/devcon-grants/"` was catching calls to `/api/devcon-grants`. We only want to redirect the `/en/devcon-grants`.
> Fix Devcon grants redirects

- src/components/forms/GranteeFinanceForm.tsx
This PR limits Security ID size to 18 chars
closes #106
> chore: Grantee Security ID cannot exceed 18 chars

- src/components/forms/GranteeFinanceForm.tsx
- src/components/layout/ApplicantsLayout.tsx
- src/pages/applicants/grantee-finance/index.tsx
This PR adds some UI fixes to Grantee Finance Form
- removes `applicants` tabs & hero from Grantee Finance Form page
- updates submit button width & text
closes #188
> Grantee finance form UI fixes

- src/components/forms/ProjectGrantsForm.tsx
- src/components/forms/api.ts
- src/pages/api/project-grants.ts
- src/types.ts
- src/utils/getGitHub.ts
- src/utils/index.ts
This PR makes the Project Repo field generic instead of just supporting GitHub URL's
- updates repo field on Project Grants form to make it generic
- removes unused `getGithub` util
> Generic repo field for Project Grants

- src/components/forms/NewsletterSignup.tsx
- src/components/forms/api.ts
- src/components/forms/constants.ts
- src/constants.ts
- src/pages/api/newsletter-signup.ts
This PR moves newsletter signup fetch logic to `/api`
- update fetch logic in `NewsletterSignup` to use `/api` instead
- update constants
> refactor: move newsletter signup fetch to /api

- netlify.toml
- next.config.js
- src/pages/academic-grants/apply.tsx
- src/pages/academic-grants/index.tsx
- src/pages/academic-grants/thank-you.tsx
This PR adds some redirections for the`/academic-grants` page, as the Academic Grants Round is currently closed.
`/academic-grants --> /applicants`
`/academic-grants/apply --> /applicants`
`/academic-grants/thank-you --> /applicants`
> chore: redirect /academic-grants to /applicants

- src/pages/api/academic-grants.ts
- src/pages/api/devcon-grants.ts
- src/pages/api/grantee-finance.ts
- src/pages/api/office-hours.ts
- src/pages/api/small-grants/event.ts
- src/pages/api/small-grants/project.ts
- src/types.ts
This PR adds body requests data typing to avoid issues on destructuring for API routes. By default, the `NextApiRequest` type sets body data types as `any`.
> chore: add body request data typings to avoid issues on destructuring

- src/pages/merge-data-challenge/index.tsx
- Change `ethstaker` and `ETHStaker` to a consistent spelling of `EthStaker`
> Consistent spelling of EthStaker

- src/components/UI/PageMetadata.tsx
We were hardcoding the home hero image on the meta tags. Now it will use the one we pass as a prop.
Now it will use the correct image while sharing links:
> Fix image displayed on PageMetadata

- src/components/UI/PageMetadata.tsx
Update Twitter title tag to use the page title vs. default site title.
None, just noticed e.g. on TG that it's pulling in the wrong title tag:
> Fix twitter title

- src/utils/getWebsite.ts
- Fixes the bug which appends `https://` to valid url strings
https://github.com/ethereum/esp-website/issues/242
> fix bug which appends https:// to urls that have http or https already

- netlify.toml
Temporary solution until we tackle https://www.notion.so/efdn/ESP-Closed-round-banner-20ae7490c963459f89cd1e26cf745062
> Add redirects from closed applications to `/applicants` page

- src/components/UI/common/BannerApplicationClosed.tsx
Adds copy to redirect users to `/applicants` page.
You can see the new copy here: https://deploy-preview-257--ecosystem-support.netlify.app/layer-2-grants
> Update copy on the `BannerApplicationClosed`

- src/components/forms/AccountAbstractionGrantsForm.tsx
- src/pages/api/account-abstraction-grants.ts
- src/types.ts
Added a missing field in the Account Abstraction form. The missing field is `website`. It is the same field & copy we are using in the AGR (https://esp.ethereum.foundation/academic-grants/apply).
> Add proposal field on the Account Abstraction form

- src/constants.ts
Martin realized that the jobs link still goes to BambooHR, while it should lead to the EF lever page.
> update EF Jobs page to lever

- src/pages/_app.tsx
Matomo Cloud migration is complete.
- Removes the temporary secondary tracker
- Updated the env vars in Netlify for new Matomo endpoints (`NEXT_PUBLIC_MATOMO_URL` and `NEXT_PUBLIC_MATOMO_SITE_ID`)
> Remove temporary Matomo tracker

- src/components/UI/common/ThankYouBody.tsx
The page currently redirects to https://esp.ethereum.foundation/applicants/small-grants/applicants/small-grants
#310
> fix(UI): the redirect page of samll-grant/thank-you

- src/components/forms/SmallGrantsForm.tsx
- Adds bold to a sentence in small grants form to make it more obvious to users
From Discord: ["@pablop would it be possible to get this text bolded on the Small Grants and Project Grants application forms? “Additional questions will appear based on your selection.” Apparently, people don’t see it."](https://discord.com/channels/420394352083337236/998689173542273167/1181648073391357993)
> Update SmallGrantsForm styling for clarity

- src/components/forms/GranteeFinanceForm.tsx
- src/components/forms/api.ts
- src/components/forms/constants.ts
Removes the Other option from `l2Network` field and make it required.
Preview: https://deploy-preview-368--ecosystem-support.netlify.app/applicants/grantee-finance
#360
> Grantee finance fix

- .gitignore
Ignore all files under the .cursor directory as users will use this directory for personal IDE config
> Ignore cursor rules
